import "./router.js";

import InputWrapper from "./js/components/InputWrapper.js";
import SignUp from "./js/components/SignUp.js";
import SignIn from "./js/components/LoginForm.js";
import NavbarOnTop from "./js/components/Navbar.js";
import PopularFilm from "./js/components/PopularFilm.js";
import Footer from "./js/components/Navbar.js";
import ContainerBox from "./js/components/index.js";
import FilmContainer from "./js/components/FilmContainer.js";
import FilmComponent from "./js/components/Films.js";
import SearchBar from "./js/components/SearchBar.js";
import FilmListSearch from "./js/components/FilmListSearch.js";
import InputComponent from "./js/components/InputComponent.js";
import ProfileManager from "./js/components/ProfileManager.js";
import StatisticData from "./js/components/StatisticData.js";
import PersonalStatistic from "./js/components/PersonalStatistic.js";
import UserAvatar from "./js/components/UserAvatar.js";
import AvatarWrapper from "./js/components/AvatarWrapper.js";
import RecommendItem from "./js/components/RecommendItem.js";
import RecommendContainer from "./js/components/RecommendContainer.js";
import UserProfile from "./js/components/UserProfile.js";
import LiveFilm from "./js/components/LiveFilm.js";
// import RatingComponent from "./js/components/RatingComponent.js";
import RatingList from "./js/components/RatingList.js";
